package kauppa.test;
// Generated by ComTest BEGIN
import kanta.SailoException;
import java.io.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import kauppa.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.08 13:15:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HenkilotTest {


  // Generated by ComTest BEGIN  // Henkilot: 31

  private Henkilot henkilot; 
  private String tiedNimi; 
  private File ftied; 

  @Before
  public void alusta() throws SailoException {
     tiedNimi = "testikauppa"; 
     ftied = new File(tiedNimi+".db"); 
     ftied.delete(); 
     henkilot = new Henkilot(tiedNimi); 
  }

  @After
  public void siivoa() {
     ftied.delete(); 
  }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa86 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa86() throws SailoException {    // Henkilot: 86
    Collection<Henkilo> loytyneet = henkilot.etsi("", 1); 
    assertEquals("From: Henkilot line: 90", 0, loytyneet.size()); 
    Henkilo henkilo1 = new Henkilo(), henkilo2 = new Henkilo(); 
    henkilot.lisaa(henkilo1); 
    henkilot.lisaa(henkilo2); 
    loytyneet = henkilot.etsi("", 1); 
    assertEquals("From: Henkilot line: 97", 2, loytyneet.size()); 
    try {
    henkilot.lisaa(henkilo1); 
    fail("Henkilot: 100 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    Henkilo henkilo3 = new Henkilo(); Henkilo henkilo4 = new Henkilo(); Henkilo henkilo5 = new Henkilo(); 
    henkilot.lisaa(henkilo3); 
    henkilot.lisaa(henkilo4); 
    henkilot.lisaa(henkilo5); 
    loytyneet = henkilot.etsi("", 1); 
    assertEquals("From: Henkilot line: 107", 5, loytyneet.size()); 
    Iterator<Henkilo> i = loytyneet.iterator(); 
    assertEquals("From: Henkilot line: 109", henkilo1, i.next()); 
    assertEquals("From: Henkilot line: 110", henkilo2, i.next()); 
    assertEquals("From: Henkilot line: 111", henkilo3, i.next()); 
  } // Generated by ComTest END
}