package kauppa.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kauppa.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.08 13:15:52 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class HenkiloTest {



  // Generated by ComTest BEGIN
  /** testAnna169 */
  @Test
  public void testAnna169() {    // Henkilo: 169
    Henkilo henkilo = new Henkilo(); 
    henkilo.parse("4|Katto Kassinen|040123456"); 
    assertEquals("From: Henkilo line: 172", "4", henkilo.anna(0)); 
    assertEquals("From: Henkilo line: 173", "Katto Kassinen", henkilo.anna(1)); 
    assertEquals("From: Henkilo line: 174", "040123456", henkilo.anna(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta197 */
  @Test
  public void testAseta197() {    // Henkilo: 197
    Henkilo henkilo = new Henkilo(); 
    assertEquals("From: Henkilo line: 199", null, henkilo.aseta(0,"3")); 
    assertEquals("From: Henkilo line: 200", null, henkilo.aseta(1,"Katto Kassinen")); 
    assertEquals("From: Henkilo line: 201", "Saa olla vain merkkejä: 0123456789- ", henkilo.aseta(2,"040asd123456")); 
    assertEquals("From: Henkilo line: 202", null, henkilo.aseta(2,"040-124321")); 
    assertEquals("From: Henkilo line: 203", null, henkilo.aseta(2,"040 124321")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone232 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone232() throws CloneNotSupportedException {    // Henkilo: 232
    Henkilo henkilo = new Henkilo(); 
    henkilo.parse("1|Katto Kassinen|040 1234567"); 
    Henkilo kopio = henkilo.clone(); 
    assertEquals("From: Henkilo line: 237", henkilo.toString(), kopio.toString()); 
    henkilo.parse("1|Väiski Vemmelsääri|040 9876543"); 
    assertEquals("From: Henkilo line: 239", false, kopio.toString().equals(henkilo.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi251 */
  @Test
  public void testRekisteroi251() {    // Henkilo: 251
    Henkilo h1 = new Henkilo(); 
    assertEquals("From: Henkilo line: 253", 0, h1.getHenkilonro()); 
    h1.rekisteroi(); 
    Henkilo h2 = new Henkilo(); 
    h2.rekisteroi(); 
    int n1 = h1.getHenkilonro(); 
    int n2 = h2.getHenkilonro(); 
    n1 = n2-1; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString347 */
  @Test
  public void testToString347() {    // Henkilo: 347
    Henkilo henkilo = new Henkilo(); 
    henkilo.parse("5|Testi Testinen|014-222333"); 
    assertEquals("From: Henkilo line: 350", true, henkilo.toString().startsWith("5|Testi Testinen|014-222333")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse366 */
  @Test
  public void testParse366() {    // Henkilo: 366
    Henkilo henkilo = new Henkilo(); 
    henkilo.parse("5|Testi Testinen|014-222333"); 
    assertEquals("From: Henkilo line: 369", 5, henkilo.getHenkilonro()); 
    assertEquals("From: Henkilo line: 370", true, henkilo.toString().startsWith("5|Testi Testinen|014-222333")); 
    henkilo.rekisteroi(); 
    int n = henkilo.getHenkilonro(); 
    henkilo.parse(""+(n+4)); 
    henkilo.rekisteroi();  // ja tarkistetaan että seuraavalla kertaa tulee yhtä isompi
    assertEquals("From: Henkilo line: 375", n+4+1, henkilo.getHenkilonro()); 
  } // Generated by ComTest END
}