package kauppa.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import kanta.SailoException;
import static org.junit.Assert.*;
import org.junit.*;
import kauppa.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.07 15:13:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OsastotTest {


  // Generated by ComTest BEGIN  // Osastot: 34

  private Osastot osastot; 
  private String tiedNimi; 
  private File ftied; 

  @Before
  public void alusta() throws SailoException {
     tiedNimi = "kauppa"; 
     ftied = new File(tiedNimi+".db"); 
     ftied.delete(); 
     osastot = new Osastot(tiedNimi); 
  }

  @After
  public void siivoa() {
     ftied.delete(); 
  }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa94 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa94() throws SailoException {    // Osastot: 94
    Collection<Osasto> loytyneet = osastot.etsi("", 1); 
    assertEquals("From: Osastot line: 98", 0, loytyneet.size()); 
    Osasto osasto1 = new Osasto(), osasto2 = new Osasto(); 
    osasto1.taytaTestiTiedoilla(); osasto2.taytaTestiTiedoilla(); 
    osastot.lisaa(osasto1); 
    osastot.lisaa(osasto2); 
    loytyneet = osastot.etsi("%", 1); 
    assertEquals("From: Osastot line: 106", 2, loytyneet.size()); 
    try {
    osastot.lisaa(osasto1); 
    fail("Osastot: 109 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    Osasto osasto3 = new Osasto(); Osasto osasto4 = new Osasto(); Osasto osasto5 = new Osasto(); 
    osasto3.taytaTestiTiedoilla(); osasto4.taytaTestiTiedoilla(); osasto5.taytaTestiTiedoilla(); 
    osastot.lisaa(osasto3); 
    osastot.lisaa(osasto4); 
    osastot.lisaa(osasto5); 
    loytyneet = osastot.etsi("%", 1); 
    assertEquals("From: Osastot line: 117", 5, loytyneet.size()); 
    Iterator<Osasto> i = loytyneet.iterator(); 
    assertEquals("From: Osastot line: 119", osasto1, i.next()); 
    assertEquals("From: Osastot line: 120", osasto2, i.next()); 
    assertEquals("From: Osastot line: 121", osasto3, i.next()); 
  } // Generated by ComTest END
}