package kauppa.test;
// Generated by ComTest BEGIN
import java.io.*;
import java.util.*;
import kanta.SailoException;
import static org.junit.Assert.*;
import org.junit.*;
import kauppa.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.08 18:48:32 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TuotteetTest {


  // Generated by ComTest BEGIN  // Tuotteet: 34

  private Tuotteet tuotteet; 
  private String tiedNimi; 
  private File ftied; 

  @Before
  public void alusta() throws SailoException {
     tiedNimi = "kookauppa"; 
     ftied = new File(tiedNimi+".db"); 
     ftied.delete(); 
     tuotteet = new Tuotteet(tiedNimi); 
  }

  @After
  public void siivoa() {
     ftied.delete(); 
  }
  // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLisaa94 
   * @throws kanta.SailoException when error
   */
  @Test
  public void testLisaa94() throws kanta.SailoException {    // Tuotteet: 94
    Collection<Tuote> loytyneet = tuotteet.etsi("", 1); 
    assertEquals("From: Tuotteet line: 98", 0, loytyneet.size()); 
    Tuote tuote1 = new Tuote(), tuote2 = new Tuote(); 
    tuotteet.lisaa(tuote1); 
    tuotteet.lisaa(tuote2); 
    loytyneet = tuotteet.etsi("", 1); 
    assertEquals("From: Tuotteet line: 105", 2, loytyneet.size()); 
    try {
    tuotteet.lisaa(tuote1); 
    fail("Tuotteet: 108 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    Tuote tuote3 = new Tuote(); Tuote tuote4 = new Tuote(); Tuote tuote5 = new Tuote(); 
    tuotteet.lisaa(tuote3); 
    tuotteet.lisaa(tuote4); 
    tuotteet.lisaa(tuote5); 
    loytyneet = tuotteet.etsi("", 1); 
    assertEquals("From: Tuotteet line: 115", 5, loytyneet.size()); 
    Iterator<Tuote> i = loytyneet.iterator(); 
    assertEquals("From: Tuotteet line: 117", tuote1, i.next()); 
    assertEquals("From: Tuotteet line: 118", tuote2, i.next()); 
    assertEquals("From: Tuotteet line: 119", tuote3, i.next()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi157 
   * @throws kanta.SailoException when error
   */
  @Test
  public void testEtsi157() throws kanta.SailoException {    // Tuotteet: 157
    Tuote tuote1 = new Tuote(); tuote1.taytaTestiTiedoilla(); 
    Tuote tuote2 = new Tuote(); tuote2.taytaTestiTiedoilla(); 
    tuotteet.lisaa(tuote1); 
    tuotteet.lisaa(tuote2); 
    try {
    tuotteet.lisaa(tuote2); 
    fail("Tuotteet: 163 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); } // ei saa lisätä sama id:tä uudelleen
    Collection<Tuote> loytyneet = tuotteet.etsi("", 1); 
    assertEquals("From: Tuotteet line: 165", 2, loytyneet.size()); 
    ftied.delete(); 
  } // Generated by ComTest END
}