package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kauppa.Henkilo;
import kanta.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.31 21:08:43 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TietueTest {



  // Generated by ComTest BEGIN
  /** testInt17 */
  @Test
  public void testInt17() {    // Tietue: 17
    Henkilo henkilo = new Henkilo(); 
    assertEquals("From: Tietue line: 20", 3, henkilo.getKenttia()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testInt29 */
  @Test
  public void testInt29() {    // Tietue: 29
    Henkilo henkilo = new Henkilo(); 
    assertEquals("From: Tietue line: 31", 1, henkilo.ekaKentta()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString41 */
  @Test
  public void testString41() {    // Tietue: 41
    Henkilo henkilo = new Henkilo(); 
    assertEquals("From: Tietue line: 43", "Puhelinnumero", henkilo.getKysymys(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString53 */
  @Test
  public void testString53() {    // Tietue: 53
    Henkilo henkilo = new Henkilo(); 
    henkilo.parse("1|Katto Kassinen|040 123345"); 
    assertEquals("From: Tietue line: 56", "1", henkilo.anna(0)); 
    assertEquals("From: Tietue line: 57", "Katto Kassinen", henkilo.anna(1)); 
    assertEquals("From: Tietue line: 58", "040 123345", henkilo.anna(2)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString71 */
  @Test
  public void testString71() {    // Tietue: 71
    Henkilo henkilo = new Henkilo(); 
    assertEquals("From: Tietue line: 73", null, henkilo.aseta(0,"3")); 
    assertEquals("From: Tietue line: 74", null, henkilo.aseta(1,"Katto Kassinen")); 
    assertEquals("From: Tietue line: 75", "Saa olla vain merkkejä: 0123456789- ", henkilo.aseta(2,"040asd123456")); 
    assertEquals("From: Tietue line: 76", null, henkilo.aseta(2,"040-124321")); 
    assertEquals("From: Tietue line: 77", null, henkilo.aseta(2,"040 124321")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testTietue88 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testTietue88() throws CloneNotSupportedException {    // Tietue: 88
    Henkilo henkilo = new Henkilo(); 
    henkilo.parse("1|Katto Kassinen|040 1234567"); 
    Henkilo kopio = henkilo.clone(); 
    assertEquals("From: Tietue line: 93", henkilo.toString(), kopio.toString()); 
    henkilo.parse("1|Väiski Vemmelsääri|040 9876543"); 
    assertEquals("From: Tietue line: 95", false, kopio.toString().equals(henkilo.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testString105 */
  @Test
  public void testString105() {    // Tietue: 105
    Henkilo henkilo = new Henkilo(); 
    henkilo.parse("5|Testi Testinen|014-222333"); 
    assertEquals("From: Tietue line: 108", true, henkilo.toString().startsWith("5|Testi Testinen|014-222333")); 
  } // Generated by ComTest END
}